{{- range $namespace, $interface := .Values.catalog.interfaces }}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: salesforce-api
  namespace: {{ $namespace }}
spec:
  data:
    salesforce-api-token: 
      secret: salesforce_api_login_token
      key: service_token
{{- end }}