{{- $notifier := .Values.notifier }}
{{- if (and $notifier.deploy (($notifier.smtp).auth).user (($notifier.smtp).auth).password) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ ($notifier.smtp.auth).secretName | default "babylon-notifier-smtp-credentials" }}
  namespace: {{ $notifier.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifier
data:
  smtp_user: {{ $notifier.smtp.auth.user | b64enc }}
  smtp_password: {{ $notifier.smtp.auth.password | b64enc }}
{{- end }}
